"""Inicialização

Revision ID: 59909ed2db7b
Revises: 4bc3a1c15309
Create Date: 2023-11-16 18:10:19.100757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59909ed2db7b'
down_revision = '4bc3a1c15309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_de_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('negociavel', sa.Boolean(), nullable=False),
    sa.Column('vendido', sa.Boolean(), nullable=False),
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('tempo_duracao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('tempo_expiracao', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('secreto', sa.Boolean(), nullable=False),
    sa.Column('valor_real', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_de_venda.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cliente')
    op.drop_table('casa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qtdQuartos', sa.INTEGER(), nullable=True),
    sa.Column('qtdBanheiros', sa.INTEGER(), nullable=True),
    sa.Column('rua', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=80), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('documento', sa.VARCHAR(length=16), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=50), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lance')
    op.drop_table('post_de_venda')
    op.drop_table('carro')
    op.drop_table('usuario')
    # ### end Alembic commands ###
